name: List Open PRs

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 7-23 * * *"

permissions:
  contents: read
  pull-requests: read

jobs:
  list-open-prs:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install pnpm
        run: corepack enable pnpm && corepack prepare pnpm@latest --activate

      - name: Install dependencies
        run: pnpm install

      - name: Build PR reporter
        run: pnpm build -- --filter=@engineering-actions/pr-open-report

      - name: List open PRs
        run: pnpm list-open-prs